package com.hjp.searchlookup;
import java.util.*;
public final class RetrievalResponse {
 public final String query, ragContext, retrievalMode, embeddingModelName, engineName, rerankerName, fallbackReason; public final List<SearchResult> results; public final List<String> cardIds; public final int keywordResultCount, semanticResultCount; public final boolean fallbackUsed; public final QueryAnalysis queryAnalysis; public final RetrievalMode mode; public final long elapsedMillis,queryEmbeddingMillis;
 public RetrievalResponse(String query,List<SearchResult> results,String ragContext,String retrievalMode,String embeddingModelName,int keywordResultCount,int semanticResultCount,boolean fallbackUsed){ this(query,results,ragContext,RetrievalMode.valueOf(retrievalMode),embeddingModelName,keywordResultCount,semanticResultCount,fallbackUsed,new QueryAnalysis(query,query,query,query,Collections.emptyList())); }
 public RetrievalResponse(String query,List<SearchResult> results,String ragContext,RetrievalMode mode,String embeddingModelName,int keywordResultCount,int semanticResultCount,boolean fallbackUsed,QueryAnalysis queryAnalysis){ this(query,results,ragContext,mode,embeddingModelName,keywordResultCount,semanticResultCount,fallbackUsed,queryAnalysis,"",0L); }
 public RetrievalResponse(String query,List<SearchResult> results,String ragContext,RetrievalMode mode,String embeddingModelName,int keywordResultCount,int semanticResultCount,boolean fallbackUsed,QueryAnalysis queryAnalysis,String fallbackReason,long elapsedMillis){ this(query,results,ragContext,mode,embeddingModelName,keywordResultCount,semanticResultCount,fallbackUsed,queryAnalysis,fallbackReason,elapsedMillis,0L); }
 public RetrievalResponse(String query,List<SearchResult> results,String ragContext,RetrievalMode mode,String embeddingModelName,int keywordResultCount,int semanticResultCount,boolean fallbackUsed,QueryAnalysis queryAnalysis,String fallbackReason,long elapsedMillis,long queryEmbeddingMillis){ this.query=query==null?"":query; this.results=Collections.unmodifiableList(new ArrayList<>(results==null?Collections.emptyList():results)); List<String> ids=new ArrayList<>(); for(SearchResult r:this.results) ids.add(r.cardId); this.cardIds=Collections.unmodifiableList(ids); this.ragContext=ragContext==null?"":ragContext; this.mode=mode==null?RetrievalMode.HYBRID:mode; this.retrievalMode=this.mode.name(); this.embeddingModelName=embeddingModelName; this.engineName=embeddingModelName; this.rerankerName="reciprocal-rank-fusion"; this.keywordResultCount=keywordResultCount; this.semanticResultCount=semanticResultCount; this.fallbackUsed=fallbackUsed; this.queryAnalysis=queryAnalysis; this.fallbackReason=fallbackReason==null?"":fallbackReason; this.elapsedMillis=Math.max(0L,elapsedMillis); this.queryEmbeddingMillis=Math.max(0L,queryEmbeddingMillis); }
 public RetrievalResponse(String query,List<SearchResult> results,String ragContext,String engineName,String rerankerName){ this(query,results,ragContext,RetrievalMode.HYBRID,engineName,0,0,false,new QueryAnalysis(query,query,query,query,Collections.emptyList())); }
}
