package com.example.hjp.deviceeval

// Generated from device-evidence/src/main/kotlin/com/example/hjp/deviceeval/DeviceRunEvidenceV7.kt by tools/ryeong_official_v8/retarget_device_runner_v8.py.
// The substitution list is declared in that file and the generated bytes are re-derived and
// compared by its --verify mode, so "nothing else changed" is checked rather than claimed.
// The measurement is v6's, unchanged, reached through v7 unchanged: only the run identity,
// the namespace and the class names are v8's. The raw schema stays ryeong_v6_raw_turn/v1 and
// the evidence contract stays DeviceRunEvidenceV7, both on purpose — v8 changed the
// characterization oracle and the JVM verdict model, and changed nothing that measures.

// Generated from device-evidence/src/main/kotlin/com/example/hjp/deviceeval/DeviceRunEvidenceV6.kt by tools/ryeong_official_v7/retarget_device_runner_v7.py.
// The substitution list is declared in that file and the generated bytes are re-derived and
// compared by its --verify mode, so "nothing else changed" is checked rather than claimed.
// The measurement is v6's, unchanged: only the run identity, the namespace and the class
// names are v7's, and the raw schema stays ryeong_v6_raw_turn/v1 on purpose.

import java.io.File
import java.io.FileOutputStream

/**
 * What a v8 device run owns, refuses, and promises about its own evidence.
 *
 * One implementation, compiled into both the instrumentation APK and the host unit tests, so a rule
 * proved on the host is the rule the device obeys. This is the v8 copy: the v5 contract is frozen
 * and pinned, and the two differ in exactly three places —
 *
 *  1. the run identifiers and directory names are v7's;
 *  2. every v3, v4 *and v5* device directory is now foreign, so a v8 run cannot write into a
 *     namespace whose evidence is already immutable;
 *  3. the raw schema is `ryeong_v6_raw_turn/v1`, which records the dataset contract each turn was
 *     scored against — including which of the four states `expected_slots` was in — and the session
 *     state each scenario opened with.
 *
 * The third is the reason this file exists at all. `ryeong_v5_raw_turn/v1` recorded neither, so a
 * reader of a v5 record cannot check its own slot classification against the dataset, and
 * `session_reset_correctness` has to fall back to a weaker predicate. A v8 record can answer both.
 *
 * Everything else is v5's, deliberately unchanged: one invocation taken by an atomic file creation,
 * a durable per-turn stream, promotion by rename only after the inventory matches, and a refusal log
 * as the only file a refused run may write.
 */
object DeviceRunEvidenceV8 {

    const val SCHEMA = "ryeong_v8_device_run/v1"
    const val RAW_TURN_SCHEMA = "ryeong_v6_raw_turn/v1"

    /**
     * The fields `ryeong_v6_raw_turn/v1` adds over `ryeong_v5_raw_turn/v1`.
     *
     * Declared here rather than only in the writer, so the host contract test can assert that a
     * device record carries every field the host readers need — before a device is ever connected.
     */
    val ADDED_RAW_FIELDS: List<String> = listOf(
        "expected_slots_state",
        "expected_slots_declared",
        "expected_focus_declared",
        "expected_focus",
        "dataset_expected_route_present",
        "dataset_gold_card_ids_present",
        "dataset_no_cards_present",
        "scenario_opened_with_selected_contact",
        "scenario_opened_with_history",
        "scenario_completed",
    )

    /** The four states `expected_slots` can be in. Folding any two of them is the v5 defect. */
    val SLOT_STATES: List<String> = listOf("MISSING", "NULL", "EMPTY", "POPULATED")

    /** Which run this is. Everything else follows from it. */
    enum class RunMode(
        val runId: String,
        val directoryName: String,
        val countsAsOfficialInvocation: Boolean,
        val scenarioLimitAllowed: Boolean,
    ) {
        /**
         * A short shakeout. It may cap the scenario count, it never claims to be a measurement, and
         * it does not consume the official invocation.
         */
        SMOKE(
            runId = "RYEONG_PRODUCTION_COMPATIBILITY_V8_SMOKE_DEVICE",
            directoryName = "ryeong_device_eval_v8_smoke",
            countsAsOfficialInvocation = false,
            scenarioLimitAllowed = true,
        ),

        /**
         * `RUN_D8`. Exactly one invocation, the whole frozen set, no cap of any kind.
         */
        OFFICIAL(
            runId = "RYEONG_PRODUCTION_COMPATIBILITY_V8_RUN_D8_DEVICE_ACTUAL_MODEL_BASELINE",
            directoryName = "ryeong_device_eval_v8_official",
            countsAsOfficialInvocation = true,
            scenarioLimitAllowed = false,
        ),
    }

    /**
     * Directory names a v8 run must never write into.
     *
     * v5's list stopped at v4. Adding the v5 directories here is not housekeeping: RUN_D5 was never
     * executed, so `ryeong_device_eval_v5_official` is an *empty* namespace, and an empty namespace
     * is exactly the kind a v8 run could fill without anything looking wrong.
     */
    val FOREIGN_DIRECTORIES: Set<String> = setOf(
        "ryeong_device_eval_v3",
        "ryeong_device_eval_v4_smoke",
        "ryeong_device_eval_v4_official",
        "ryeong_device_eval_v5_smoke",
        "ryeong_device_eval_v5_official",
        "ryeong_device_eval_v6_smoke",
        "ryeong_device_eval_v6_official",
        "ryeong_device_eval_v7_smoke",
        "ryeong_device_eval_v7_official",
    )

    const val PARTIAL_SUFFIX = ".partial"
    const val RAW_TURNS = "raw_turns.jsonl"
    const val RESULT = "device_result.json"
    const val STATUS = "device_run_status.json"
    const val INVOCATION_MARKER = "invocation.marker"
    const val REFUSAL_LOG = "refused_invocations.log"
    const val PROGRESS = "progress_status.json"

    /** Artefacts whose presence proves a run of this mode already happened. */
    val FINAL_ARTIFACTS = listOf(RAW_TURNS, RESULT, STATUS)

    /** Everything a run of one mode owns. Built from the mode, never passed in piecemeal. */
    class Paths(val root: File, val mode: RunMode) {
        val directory: File = File(root, mode.directoryName)
        val rawTurns: File get() = File(directory, RAW_TURNS)
        val rawTurnsPartial: File get() = File(directory, RAW_TURNS + PARTIAL_SUFFIX)
        val result: File get() = File(directory, RESULT)
        val status: File get() = File(directory, STATUS)
        val invocationMarker: File get() = File(directory, INVOCATION_MARKER)
        val refusalLog: File get() = File(directory, REFUSAL_LOG)
        val progress: File get() = File(directory, PROGRESS)

        init {
            requireNotForeign(directory.name)
        }

        fun prepare(): Paths = apply { directory.mkdirs() }

        fun existingFinalArtifacts(): List<String> =
            FINAL_ARTIFACTS.filter { File(directory, it).isFile }

        fun stalePartials(): List<String> =
            directory.listFiles { f -> f.name.endsWith(PARTIAL_SUFFIX) }
                .orEmpty().map { it.name }.sorted()
    }

    /**
     * Refuses a directory that belongs to an earlier evaluation version.
     *
     * [RunMode] already makes it impossible to *ask* for one, which is the point — but "impossible by
     * construction" is a property of today's enum, and a v7 that adds a mode by copying this file is
     * exactly when a name collision would slip through.
     */
    fun requireNotForeign(directoryName: String) {
        require(directoryName !in FOREIGN_DIRECTORIES) {
            "a v8 run may not write into $directoryName — that directory belongs to an earlier " +
                "evaluation version and its evidence is immutable"
        }
    }

    /** Why an official run was refused, or [Claimed] when it was not. */
    sealed interface ClaimResult {
        data class Claimed(val markerContents: String) : ClaimResult
        data class Refused(val code: String, val detail: String) : ClaimResult
    }

    /**
     * Takes the single official invocation, or explains why it cannot.
     *
     * The order matters: existing evidence is checked before the marker is attempted, so a directory
     * holding a finished run reports *that* rather than a marker collision. A refusal never touches a
     * final artefact; it appends to [Paths.refusalLog], the only file a refused run writes.
     */
    object OfficialRunGuard {

        fun claim(paths: Paths, markerContents: String, nowIso: String): ClaimResult {
            if (!paths.mode.countsAsOfficialInvocation) {
                return ClaimResult.Claimed(markerContents)
            }
            paths.prepare()
            val existing = paths.existingFinalArtifacts()
            if (existing.isNotEmpty()) {
                return refuse(paths, "RUN_ALREADY_EXECUTED",
                    "the directory already holds ${existing.joinToString(", ")}", nowIso)
            }
            val stale = paths.stalePartials()
            if (stale.isNotEmpty()) {
                return refuse(paths, "STALE_PARTIAL_PRESENT",
                    "an earlier attempt left ${stale.joinToString(", ")}; that evidence is not " +
                        "overwritten and this invocation is refused", nowIso)
            }
            val created = try {
                paths.invocationMarker.createNewFile()
            } catch (error: java.io.IOException) {
                return refuse(paths, "MARKER_NOT_WRITABLE", error.message.orEmpty(), nowIso)
            }
            if (!created) {
                return refuse(paths, "INVOCATION_ALREADY_CLAIMED",
                    "the invocation marker already exists", nowIso)
            }
            writeDurably(paths.invocationMarker, markerContents)
            return ClaimResult.Claimed(markerContents)
        }

        fun invocationCount(paths: Paths): Int = if (paths.invocationMarker.isFile) 1 else 0

        private fun refuse(paths: Paths, code: String, detail: String, nowIso: String): ClaimResult {
            paths.refusalLog.appendText("$nowIso $code $detail\n", Charsets.UTF_8)
            return ClaimResult.Refused(code, detail)
        }
    }

    /**
     * One JSON object per line, flushed and synced per turn.
     *
     * A flush reaches the operating system; a sync reaches the disk. A run killed by a thermal
     * shutdown must leave what it got through, not what the page cache still happened to hold.
     */
    class DurableTurnStream(private val paths: Paths) : AutoCloseable {

        private val stream = FileOutputStream(paths.rawTurnsPartial, true)
        private var written = 0

        val turnsWritten: Int get() = written

        /**
         * [line] must be *exactly* one complete JSON object with no embedded newline.
         *
         * The brace balance is checked, not just the first and last character: `{"a":1}{"b":2}`
         * starts with `{` and ends with `}` and is two objects on one line, which every reader
         * would report as a parse error after the run rather than as a refusal during it.
         */
        fun append(line: String) {
            require(!line.contains('\n')) { "a raw turn record may not contain a newline" }
            require(line.startsWith("{") && line.endsWith("}")) {
                "a raw turn record must be exactly one JSON object"
            }
            require(isExactlyOneObject(line)) {
                "a raw turn record must be exactly one JSON object, not several on one line"
            }
            stream.write((line + "\n").toByteArray(Charsets.UTF_8))
            stream.flush()
            stream.fd.sync()
            written += 1
        }

        override fun close() {
            stream.flush()
            stream.fd.sync()
            stream.close()
        }

        /**
         * Whether the depth returns to zero exactly once, at the end.
         *
         * The same brace-balance scan the independent readers use, applied at the moment of
         * writing rather than at the moment of reading.
         */
        private fun isExactlyOneObject(line: String): Boolean {
            var depth = 0
            var inString = false
            var escaped = false
            line.forEachIndexed { index, character ->
                if (inString) {
                    when {
                        escaped -> escaped = false
                        character == '\\' -> escaped = true
                        character == '"' -> inString = false
                    }
                    return@forEachIndexed
                }
                when (character) {
                    '"' -> inString = true
                    '{', '[' -> depth += 1
                    '}', ']' -> {
                        depth -= 1
                        // A depth of zero before the last character means the object ended and
                        // something else began.
                        if (depth == 0 && index != line.length - 1) return false
                    }
                }
            }
            return depth == 0 && !inString
        }

        /**
         * Promotes the partial record to its final name, or explains why it may not be promoted.
         *
         * A run that did not produce the declared inventory keeps its partial file and gets no
         * result. That is the honest artefact of a run that did not finish.
         */
        fun promote(gate: RunInventoryGate.Result): List<String> {
            if (!gate.complete) return gate.failures
            if (!paths.rawTurnsPartial.isFile) return listOf("NO_PARTIAL_RECORD")
            if (!paths.rawTurnsPartial.renameTo(paths.rawTurns)) {
                return listOf("PROMOTION_RENAME_FAILED")
            }
            return emptyList()
        }
    }

    /**
     * Whether the record the run produced is the record it was supposed to produce.
     *
     * An official run is held to the whole frozen inventory. A smoke run is not — it may be capped —
     * but duplicates, missing turns and a crash are failures in either mode, because none of those
     * is something a cap can explain.
     */
    object RunInventoryGate {

        data class Expected(
            val scenarios: Int,
            val turns: Int,
            val kinds: Int,
            val depthCounts: Map<Int, Int>,
        )

        data class Observed(
            val scenarios: Int,
            val turns: Int,
            val kinds: Int,
            val depthCounts: Map<Int, Int>,
            val duplicateTurnKeys: List<String>,
            val missingTurnKeys: List<String>,
            val crashed: Boolean,
            /** v6: a record whose turns do not all carry a declared slot state is not scorable. */
            val turnsWithoutSlotState: List<String> = emptyList(),
        )

        data class Result(val failures: List<String>) {
            val complete: Boolean get() = failures.isEmpty()
        }

        fun check(expected: Expected, observed: Observed, mode: RunMode): Result {
            val failures = mutableListOf<String>()
            fun require(condition: Boolean, message: String) {
                if (!condition) failures += message
            }
            require(!observed.crashed, "RUN_CRASHED: the run did not reach the end")
            require(observed.duplicateTurnKeys.isEmpty(),
                "DUPLICATE_TURNS: ${observed.duplicateTurnKeys}")
            require(observed.missingTurnKeys.isEmpty(),
                "MISSING_TURNS: ${observed.missingTurnKeys}")
            require(observed.turnsWithoutSlotState.isEmpty(),
                "RAW_SCHEMA_FIELD_MISSING: expected_slots_state absent on " +
                    "${observed.turnsWithoutSlotState}")
            if (mode == RunMode.OFFICIAL) {
                require(observed.scenarios == expected.scenarios,
                    "SCENARIO_COUNT: ${observed.scenarios} != ${expected.scenarios}")
                require(observed.turns == expected.turns,
                    "TURN_COUNT: ${observed.turns} != ${expected.turns}")
                require(observed.kinds == expected.kinds,
                    "KIND_COUNT: ${observed.kinds} != ${expected.kinds}")
                require(observed.depthCounts == expected.depthCounts,
                    "DEPTH_INVENTORY: ${observed.depthCounts} != ${expected.depthCounts}")
            }
            return Result(failures)
        }
    }

    /**
     * Rejects a scenario cap on a run that may not have one.
     *
     * An official run that quietly honoured `-e ryeongScenarioLimit 5` would produce a 5-scenario
     * result carrying the official run identifier, and no later reader could tell.
     */
    fun requireScenarioLimitAllowed(mode: RunMode, scenarioLimit: Int) {
        if (scenarioLimit > 0 && !mode.scenarioLimitAllowed) {
            error(
                "$mode refuses a scenario limit (got $scenarioLimit). A capped run is a smoke run; " +
                    "execute ${RunMode.SMOKE.runId} instead.",
            )
        }
    }

    /** Writes [contents] and forces it to storage, so a later crash cannot lose it. */
    fun writeDurably(target: File, contents: String) {
        FileOutputStream(target).use { stream ->
            stream.write(contents.toByteArray(Charsets.UTF_8))
            stream.flush()
            stream.fd.sync()
        }
    }

    /**
     * Replaces [target] atomically: write a sibling temporary file, sync it, rename over the target.
     */
    fun replaceAtomically(target: File, contents: String) {
        val temporary = File(target.parentFile, target.name + PARTIAL_SUFFIX)
        writeDurably(temporary, contents)
        if (!temporary.renameTo(target)) {
            temporary.delete()
            error(
                "atomic replace is not available for ${target.absolutePath}; write the run's " +
                    "evidence to app-private storage instead of this location",
            )
        }
    }
}
